baseURL = 'https://ciupei-timotei-30323.github.io/'
languageCode = 'en-us'
title = "Timo's blog"

theme = "not-much"



[params]
theme = "dark"
palette = "dracula"
showThemeNotice = false
showPostsSummary = true


# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1


  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/ciupei-timotei-30323/"
    weight = 4

    [[menu.main]]
    identifier = "linkedin"
    name = "linkedin"
    title = "linkedin"
    url = "https://ro.linkedin.com/in/timotei-ciupei-16aa55342"
    weight = 5

    [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "https://www.dropbox.com/scl/fi/v8ojc8nq0mbjcv7flugks/Timotei_Ciupei_cv-2.pdf?rlkey=nv4nvaac2jd2ki0s13qrzbw4p&dl=0"
    weight = 6


   [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 2